version: '3'
services:
  python-docker-graph:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # ホストのDockerソケットをマウント
      - ./output:/usr/src/app/output               # ホストのoutputディレクトリをコンテナにマウント
    command: ["python3", "app.py"]
